In [242]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics
import numpy as np
import pandas as pd


# Path of the file to read
train = 'train.csv'
test = 'test.csv'

train_data = pd.read_csv(train)       #讀取.csv檔
test_data = pd.read_csv(test)


In [243]:
X = train_data[['battery_power','blue','clock_speed','dual_sim','fc',         #定義輸入、輸出訓練資料
'four_g','int_memory','m_dep','mobile_wt','n_cores','pc','px_height',
'px_width','ram','sc_h','sc_w','talk_time','three_g','touch_screen','wifi']]
Y = train_data[['price_range']]               

In [244]:
X_train, X_validation, y_train, y_validation = train_test_split(X, Y,test_size=0.3) #分割訓練集、驗證集

In [245]:
clf=tree.DecisionTreeClassifier(criterion='entropy').fit(X_train,y_train)


In [246]:
y_pre = clf.predict(X_validation)#驗證模型好不好
y_pre

array([1, 3, 3, 3, 3, 2, 3, 3, 1, 1, 0, 2, 1, 0, 2, 1, 2, 2, 0, 1, 2, 1,
       0, 1, 2, 0, 3, 0, 1, 3, 1, 0, 0, 1, 0, 1, 0, 3, 2, 2, 0, 2, 0, 2,
       1, 1, 2, 3, 0, 3, 2, 0, 3, 0, 3, 3, 1, 0, 1, 0, 2, 0, 1, 3, 0, 2,
       2, 0, 1, 3, 3, 1, 3, 0, 1, 2, 3, 0, 1, 3, 2, 1, 3, 0, 3, 1, 2, 0,
       3, 1, 0, 0, 3, 3, 3, 3, 2, 0, 2, 1, 0, 3, 2, 2, 3, 0, 2, 3, 1, 1,
       1, 0, 1, 3, 0, 3, 1, 1, 1, 0, 1, 0, 1, 3, 2, 2, 0, 1, 2, 3, 1, 3,
       3, 1, 0, 3, 1, 3, 0, 3, 0, 2, 3, 1, 0, 1, 3, 3, 3, 0, 3, 2, 3, 1,
       1, 0, 1, 2, 3, 2, 0, 3, 2, 2, 0, 3, 2, 1, 0, 0, 2, 3, 3, 1, 1, 2,
       3, 3, 1, 1, 2, 2, 2, 2, 3, 1, 2, 2, 1, 0, 3, 3, 3, 3, 0, 0, 0, 3,
       1, 0, 0, 0, 0, 1, 2, 0, 0, 3, 3, 0, 3, 0, 2, 2, 0, 0, 2, 1, 1, 0,
       0, 2, 3, 0, 1, 2, 3, 0, 1, 2, 0, 3, 3, 3, 0, 2, 2, 0, 2, 2, 0, 2,
       1, 3, 3, 0, 1, 3, 3, 0, 3, 0, 3, 3, 2, 2, 3, 1, 0, 3, 0, 3, 1, 1,
       1, 3, 3, 3, 3, 2, 1, 3, 0, 1, 0, 1, 0, 3, 0, 2, 0, 2, 2, 0, 0, 3,
       2, 0, 2, 3, 0, 0, 3, 3, 2, 3, 3, 0, 0, 1, 1,

In [247]:
clf.score(X_train,y_train)#準確度分析


1.0

In [248]:
clf.score(X_validation,y_validation)#準確度分析

0.8516666666666667

In [249]:
clf_matrics = metrics.confusion_matrix(y_validation,y_pre) #(真實值，預測值) 混淆矩陣
clf_matrics 

array([[137,   6,   0,   0],
       [ 23, 118,  16,   0],
       [  0,  16, 111,  16],
       [  0,   0,  12, 145]], dtype=int64)

In [250]:
from sklearn.metrics import precision_recall_fscore_support
print("Accuracy:",metrics.accuracy_score(y_validation, y_pre))#準確率
print("Precision:",metrics.precision_score(y_validation,y_pre,average=None))#精準度
print("Recall:",metrics.recall_score(y_validation,y_pre,average=None))#召回率
print("F1_score:",metrics.f1_score(y_validation,y_pre,average=None))#F1-score 

Accuracy: 0.8516666666666667
Precision: [0.85625    0.84285714 0.79856115 0.90062112]
Recall: [0.95804196 0.75159236 0.77622378 0.92356688]
F1_score: [0.90429043 0.79461279 0.78723404 0.91194969]


In [251]:
precision_recall_fscore_support(y_validation,y_pre,average=None) #support

(array([0.85625   , 0.84285714, 0.79856115, 0.90062112]),
 array([0.95804196, 0.75159236, 0.77622378, 0.92356688]),
 array([0.90429043, 0.79461279, 0.78723404, 0.91194969]),
 array([143, 157, 143, 157], dtype=int64))

In [252]:
X_test = test_data[['battery_power','blue','clock_speed','dual_sim','fc',
'four_g','int_memory','m_dep','mobile_wt','n_cores','pc','px_height',
'px_width','ram','sc_h','sc_w','talk_time','three_g','touch_screen','wifi']]

In [253]:
Y_test = clf.predict(X_test)#預測
Y_test

array([3, 3, 2, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 0, 2, 0, 2, 1, 3, 2, 0, 2,
       1, 1, 3, 0, 2, 0, 2, 0, 2, 0, 3, 0, 0, 1, 3, 1, 2, 0, 1, 2, 0, 0,
       0, 1, 0, 3, 1, 2, 1, 0, 2, 0, 3, 1, 2, 1, 0, 3, 3, 3, 0, 1, 1, 1,
       1, 3, 1, 2, 1, 2, 2, 3, 3, 0, 2, 0, 2, 3, 1, 3, 3, 0, 3, 0, 3, 1,
       3, 0, 0, 1, 2, 0, 2, 1, 0, 2, 1, 2, 1, 0, 0, 3, 0, 2, 0, 1, 2, 3,
       3, 2, 1, 3, 3, 3, 3, 2, 3, 0, 0, 3, 1, 1, 2, 0, 3, 2, 3, 2, 0, 2,
       1, 0, 3, 0, 1, 0, 3, 2, 1, 3, 1, 3, 2, 3, 3, 2, 2, 3, 2, 3, 1, 0,
       2, 1, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 0, 3, 0, 0, 0, 2, 1, 0, 1,
       0, 0, 1, 3, 1, 0, 0, 0, 1, 3, 2, 1, 0, 0, 0, 0, 0, 3, 2, 1, 2, 2,
       2, 3, 1, 2, 3, 3, 3, 2, 2, 1, 0, 0, 1, 2, 0, 3, 3, 3, 0, 2, 0, 3,
       2, 2, 3, 1, 0, 1, 0, 3, 0, 1, 0, 2, 2, 1, 2, 1, 3, 0, 3, 1, 2, 0,
       0, 2, 1, 3, 3, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 2, 1, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 0, 2, 3, 1, 1, 3, 2, 1, 3, 0, 1, 3, 1, 0, 3, 3, 3,
       3, 2, 1, 3, 2, 2, 3, 1, 2, 1, 2, 0, 3, 3, 1,