In [25]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Path of the file to read
train = 'train.csv'
test = 'test.csv'

train_data = pd.read_csv(train)       #讀取.csv檔
test_data = pd.read_csv(test)



In [26]:
X = train_data[['battery_power','blue','clock_speed','dual_sim','fc',         #定義輸入、輸出訓練資料
'four_g','int_memory','m_dep','mobile_wt','n_cores','pc','px_height',
'px_width','ram','sc_h','sc_w','talk_time','three_g','touch_screen','wifi']]
Y = train_data[['price_range']]                                               


In [27]:
X_train, X_validation, y_train, y_validation = train_test_split(X, Y,test_size=0.2,random_state=20) #分割訓練集、驗證集

In [28]:
knn = KNeighborsClassifier(n_neighbors=3,p=2,weights='distance',algorithm='brute')
knn.fit(X_train,y_train)

D:\Python\Python37\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(algorithm='brute', n_neighbors=3, weights='distance')

In [29]:
y_pre = knn.predict(X_validation)#驗證模型好不好
y_pre

array([3, 2, 1, 1, 3, 2, 2, 1, 3, 2, 0, 2, 3, 2, 3, 2, 2, 1, 2, 3, 3, 3,
       0, 0, 3, 2, 3, 1, 3, 0, 3, 2, 0, 2, 0, 0, 3, 0, 2, 0, 2, 3, 3, 1,
       0, 2, 1, 1, 3, 1, 3, 0, 1, 1, 1, 0, 3, 1, 1, 3, 3, 0, 2, 1, 1, 3,
       1, 2, 0, 1, 1, 3, 3, 0, 0, 2, 0, 0, 2, 0, 1, 1, 2, 2, 0, 0, 2, 2,
       3, 0, 3, 2, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 3, 2, 1, 2, 2, 2,
       1, 2, 2, 1, 3, 3, 3, 0, 3, 1, 2, 0, 1, 0, 2, 3, 0, 2, 1, 0, 2, 0,
       0, 1, 1, 1, 3, 2, 2, 2, 1, 2, 2, 1, 0, 1, 3, 1, 2, 0, 2, 0, 2, 0,
       3, 3, 2, 2, 1, 2, 0, 0, 3, 3, 2, 2, 2, 2, 3, 3, 1, 2, 2, 1, 1, 3,
       1, 2, 0, 3, 1, 1, 2, 1, 1, 0, 2, 1, 0, 3, 2, 3, 1, 3, 2, 2, 1, 2,
       3, 1, 0, 1, 1, 1, 2, 1, 2, 3, 3, 0, 3, 3, 1, 3, 0, 0, 2, 2, 2, 3,
       1, 0, 2, 2, 3, 0, 3, 1, 2, 1, 0, 1, 1, 2, 1, 3, 0, 1, 3, 0, 2, 1,
       1, 2, 3, 0, 0, 1, 0, 2, 1, 2, 3, 0, 2, 3, 1, 3, 1, 0, 1, 3, 2, 0,
       1, 1, 1, 1, 1, 3, 0, 1, 2, 0, 3, 3, 3, 3, 3, 3, 2, 0, 3, 0, 0, 0,
       1, 3, 2, 2, 3, 3, 3, 1, 1, 3, 1, 1, 2, 2, 3,

In [30]:
knn.score(X_train,y_train) #準確度分析

1.0

In [31]:
knn.score(X_validation,y_validation)#準確度分析

0.915

In [32]:
knn_matrics = metrics.confusion_matrix(y_validation,y_pre) #(真實值，預測值) 混淆矩陣
knn_matrics 

array([[83,  5,  0,  0],
       [ 5, 90,  3,  0],
       [ 0,  8, 98,  8],
       [ 0,  0,  5, 95]], dtype=int64)

In [33]:
from sklearn.metrics import precision_recall_fscore_support
print("Accuracy:",metrics.accuracy_score(y_validation, y_pre))#準確率
print("Precision:",metrics.precision_score(y_validation,y_pre,average=None))#精準度
print("Recall:",metrics.recall_score(y_validation,y_pre,average=None))#召回率
print("F1_score:",metrics.f1_score(y_validation,y_pre,average=None))#F1-score 

Accuracy: 0.915
Precision: [0.94318182 0.87378641 0.9245283  0.9223301 ]
Recall: [0.94318182 0.91836735 0.85964912 0.95      ]
F1_score: [0.94318182 0.89552239 0.89090909 0.93596059]


In [34]:
precision_recall_fscore_support(y_validation,y_pre,average=None) #support

(array([0.94318182, 0.87378641, 0.9245283 , 0.9223301 ]),
 array([0.94318182, 0.91836735, 0.85964912, 0.95      ]),
 array([0.94318182, 0.89552239, 0.89090909, 0.93596059]),
 array([ 88,  98, 114, 100], dtype=int64))

In [35]:
X_test = test_data[['battery_power','blue','clock_speed','dual_sim','fc',
'four_g','int_memory','m_dep','mobile_wt','n_cores','pc','px_height',
'px_width','ram','sc_h','sc_w','talk_time','three_g','touch_screen','wifi']]

In [36]:
Y_test = knn.predict(X_test)#預測
Y_test

array([3, 3, 3, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 0, 2, 0, 2, 1, 3, 2, 1, 3,
       1, 1, 3, 0, 2, 0, 3, 0, 2, 0, 3, 0, 0, 1, 3, 1, 2, 1, 1, 2, 0, 0,
       0, 1, 0, 3, 1, 2, 1, 0, 3, 0, 3, 1, 3, 1, 1, 3, 3, 2, 0, 2, 1, 1,
       1, 3, 1, 2, 1, 2, 2, 3, 3, 0, 2, 0, 2, 3, 0, 3, 3, 0, 3, 0, 3, 1,
       2, 0, 1, 2, 2, 0, 2, 2, 1, 2, 1, 2, 1, 0, 0, 3, 0, 2, 0, 1, 2, 3,
       3, 3, 1, 3, 3, 3, 3, 2, 3, 0, 0, 3, 2, 1, 2, 0, 3, 2, 3, 1, 0, 2,
       1, 1, 3, 1, 1, 0, 3, 2, 1, 2, 1, 3, 2, 3, 3, 3, 2, 3, 2, 3, 0, 0,
       3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 1, 0, 3, 0, 0, 0, 2, 1, 0, 1,
       0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 1, 3, 1, 0, 2, 2,
       3, 3, 1, 1, 2, 2, 3, 2, 2, 1, 1, 0, 1, 2, 0, 2, 3, 3, 0, 2, 0, 3,
       2, 2, 3, 1, 0, 1, 0, 3, 0, 1, 0, 2, 2, 1, 2, 0, 3, 0, 3, 1, 2, 0,
       0, 2, 1, 3, 3, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 1, 1, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 0, 2, 3, 2, 1, 3, 2, 0, 3, 0, 1, 2, 1, 0, 3, 2, 3,
       3, 2, 1, 3, 3, 2, 3, 1, 2, 1, 2, 0, 2, 3, 1,