In [13]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import numpy as np
import pandas as pd


# Path of the file to read
train = 'train.csv'
test = 'test.csv'

train_data = pd.read_csv(train)       #讀取.csv檔
test_data = pd.read_csv(test)



In [14]:
X = train_data[['battery_power','blue','clock_speed','dual_sim','fc',         #定義輸入、輸出訓練資料
'four_g','int_memory','m_dep','mobile_wt','n_cores','pc','px_height',
'px_width','ram','sc_h','sc_w','talk_time','three_g','touch_screen','wifi']]
Y = train_data[['price_range']]                                               


In [15]:
X_train, X_validation, y_train, y_validation = train_test_split(X, Y,test_size=0.3) #分割訓練集、驗證集


In [16]:
rfc=RandomForestClassifier(n_estimators=100,n_jobs = -1,random_state =50, min_samples_leaf = 10) #選擇隨機森林分類器
rfc.fit(X_train,y_train)


D:\Python\Python37\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(min_samples_leaf=10, n_jobs=-1, random_state=50)

In [17]:
y_pre = rfc.predict(X_validation)#驗證模型好不好
y_pre

array([1, 3, 1, 0, 2, 0, 3, 1, 3, 0, 1, 2, 0, 1, 1, 2, 1, 1, 2, 1, 2, 3,
       2, 3, 3, 1, 1, 3, 3, 3, 3, 1, 3, 1, 1, 0, 3, 2, 1, 0, 0, 3, 1, 0,
       0, 2, 0, 3, 1, 3, 2, 2, 0, 0, 2, 3, 2, 2, 1, 1, 0, 1, 2, 1, 1, 0,
       0, 1, 3, 1, 0, 3, 0, 0, 3, 2, 0, 1, 2, 0, 0, 0, 3, 0, 0, 1, 3, 1,
       0, 2, 2, 2, 2, 1, 2, 2, 3, 0, 3, 3, 0, 3, 3, 0, 3, 1, 0, 3, 2, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 2, 2, 1, 0, 0, 1, 3, 2, 3, 2, 3, 3, 0, 2,
       2, 1, 2, 2, 0, 3, 3, 2, 0, 3, 2, 3, 0, 3, 3, 0, 3, 1, 1, 3, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 3, 3, 0, 0, 3, 1, 3, 2, 3, 3, 1, 2, 0, 2, 3,
       3, 3, 0, 3, 2, 2, 3, 0, 1, 3, 0, 1, 3, 2, 0, 0, 3, 2, 3, 0, 2, 2,
       2, 1, 3, 3, 1, 0, 0, 3, 3, 3, 0, 1, 1, 3, 2, 3, 0, 2, 2, 0, 0, 2,
       2, 3, 1, 2, 2, 1, 0, 1, 2, 0, 3, 2, 1, 2, 2, 1, 2, 0, 1, 3, 2, 2,
       3, 2, 0, 1, 3, 1, 2, 3, 2, 3, 2, 0, 1, 3, 2, 1, 0, 3, 1, 2, 0, 3,
       0, 1, 3, 1, 0, 1, 3, 1, 2, 0, 0, 0, 1, 2, 0, 1, 2, 3, 1, 0, 1, 3,
       0, 3, 1, 3, 0, 3, 2, 1, 2, 1, 2, 3, 0, 3, 1,

In [18]:
rfc.score(X_train,y_train) #準確度分析

0.9557142857142857

In [19]:
rfc.score(X_validation,y_validation)#準確度分析

0.8666666666666667

In [20]:
rfc_matrics = metrics.confusion_matrix(y_validation,y_pre) #(真實值，預測值) 混淆矩陣
rfc_matrics 

array([[140,  11,   0,   0],
       [  6, 125,  20,   0],
       [  0,  26, 114,  13],
       [  0,   0,   4, 141]], dtype=int64)

In [21]:
from sklearn.metrics import precision_recall_fscore_support
print("Accuracy:",metrics.accuracy_score(y_validation, y_pre))#準確率
print("Precision:",metrics.precision_score(y_validation,y_pre,average=None))#精準度
print("Recall:",metrics.recall_score(y_validation,y_pre,average=None))#召回率
print("F1_score:",metrics.f1_score(y_validation,y_pre,average=None))#F1-score 

Accuracy: 0.8666666666666667
Precision: [0.95890411 0.77160494 0.82608696 0.91558442]
Recall: [0.92715232 0.82781457 0.74509804 0.97241379]
F1_score: [0.94276094 0.79872204 0.78350515 0.94314381]


In [22]:
precision_recall_fscore_support(y_validation,y_pre,average=None) #support

(array([0.95890411, 0.77160494, 0.82608696, 0.91558442]),
 array([0.92715232, 0.82781457, 0.74509804, 0.97241379]),
 array([0.94276094, 0.79872204, 0.78350515, 0.94314381]),
 array([151, 151, 153, 145], dtype=int64))

In [23]:
X_test = test_data[['battery_power','blue','clock_speed','dual_sim','fc',
'four_g','int_memory','m_dep','mobile_wt','n_cores','pc','px_height',
'px_width','ram','sc_h','sc_w','talk_time','three_g','touch_screen','wifi']]

In [24]:
Y_test = rfc.predict(X_test)#預測
Y_test

array([2, 3, 2, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 0, 2, 0, 1, 2, 3, 2, 1, 3,
       1, 1, 3, 0, 2, 0, 2, 0, 2, 0, 3, 0, 1, 1, 3, 1, 2, 1, 1, 2, 0, 0,
       0, 1, 0, 3, 1, 2, 2, 0, 3, 0, 3, 0, 3, 1, 1, 3, 3, 2, 0, 1, 1, 1,
       1, 3, 1, 1, 1, 1, 2, 3, 3, 0, 2, 0, 2, 3, 0, 3, 3, 0, 3, 0, 3, 1,
       3, 0, 1, 1, 2, 1, 2, 1, 0, 2, 1, 3, 1, 0, 0, 3, 1, 2, 1, 1, 2, 3,
       3, 3, 1, 3, 3, 3, 3, 1, 3, 0, 0, 3, 2, 1, 1, 0, 3, 2, 3, 1, 0, 1,
       1, 1, 3, 1, 1, 0, 3, 2, 1, 3, 2, 2, 2, 3, 3, 2, 2, 3, 2, 3, 0, 0,
       2, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 0, 3, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 2, 0, 0, 0, 1, 2, 2, 2, 1, 0, 0, 0, 1, 0, 3, 1, 0, 2, 2,
       3, 3, 1, 2, 3, 3, 3, 1, 2, 1, 0, 1, 1, 3, 1, 3, 3, 3, 0, 2, 0, 3,
       2, 2, 3, 0, 0, 1, 0, 3, 0, 1, 0, 2, 1, 1, 3, 0, 2, 0, 3, 1, 2, 0,
       0, 2, 1, 3, 3, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 1, 1, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 1, 1, 3, 1, 1, 3, 2, 0, 3, 0, 1, 2, 0, 0, 3, 2, 3,
       3, 2, 1, 3, 3, 2, 3, 2, 2, 1, 1, 0, 2, 3, 1,