In [50]:
from sklearn import svm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import metrics

# Path of the file to read
train = 'train.csv'
test = 'test.csv'

train_data = pd.read_csv(train)       #讀取.csv檔
test_data = pd.read_csv(test)





In [51]:
X = train_data[['battery_power','blue','clock_speed','dual_sim','fc',         #定義輸入、輸出訓練資料
'four_g','int_memory','m_dep','mobile_wt','n_cores','pc','px_height',
'px_width','ram','sc_h','sc_w','talk_time','three_g','touch_screen','wifi']]
Y = train_data[['price_range']]                                               



In [52]:
X_train, X_validation, y_train, y_validation = train_test_split(X, Y,test_size=0.2,random_state=20) #分割訓練集、驗證集
y_validation

price_range
1556            3
1560            2
1559            2
1594            1
906             3
...           ...
959             3
1939            2
668             3
534             2
1111            3

[400 rows x 1 columns]

In [53]:
clf=svm.SVC(kernel='linear',C=1,gamma='auto')#poly多項式 rbf高斯 sigmoid       #SVM模型
clf.fit(X_train,y_train)

D:\Python\Python37\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1, gamma='auto', kernel='linear')

In [54]:
y_pre = clf.predict(X_validation)#驗證模型好不好
y_pre

array([3, 2, 1, 1, 3, 2, 2, 1, 3, 2, 0, 2, 3, 1, 3, 2, 2, 2, 2, 3, 3, 2,
       0, 0, 3, 2, 3, 1, 3, 0, 3, 2, 0, 2, 0, 0, 3, 0, 2, 0, 2, 3, 3, 1,
       0, 2, 1, 1, 3, 0, 3, 0, 1, 1, 1, 0, 3, 1, 2, 3, 3, 0, 2, 1, 1, 2,
       1, 3, 0, 1, 1, 3, 3, 0, 0, 2, 0, 0, 2, 0, 1, 1, 2, 2, 0, 0, 2, 2,
       3, 0, 3, 3, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 3, 2, 1, 2, 2, 2,
       0, 2, 2, 1, 3, 3, 3, 0, 3, 0, 2, 0, 1, 0, 2, 3, 0, 2, 1, 0, 2, 0,
       0, 1, 1, 1, 3, 2, 1, 2, 1, 2, 2, 1, 0, 1, 3, 1, 2, 0, 2, 0, 2, 0,
       3, 3, 2, 2, 1, 2, 0, 0, 3, 3, 2, 2, 2, 2, 3, 3, 1, 1, 2, 1, 1, 3,
       1, 2, 0, 3, 1, 1, 2, 1, 0, 0, 2, 1, 0, 3, 2, 3, 1, 2, 2, 2, 1, 2,
       3, 2, 1, 1, 1, 1, 2, 1, 3, 3, 3, 0, 3, 3, 1, 3, 0, 0, 3, 2, 2, 3,
       1, 0, 2, 2, 3, 0, 2, 1, 2, 2, 0, 1, 1, 2, 1, 3, 0, 1, 3, 0, 2, 1,
       1, 2, 3, 0, 1, 1, 0, 2, 1, 2, 3, 0, 2, 3, 1, 3, 1, 0, 1, 3, 2, 0,
       1, 1, 1, 1, 1, 3, 0, 1, 2, 0, 3, 3, 3, 3, 3, 3, 2, 0, 3, 0, 1, 1,
       1, 3, 2, 2, 3, 2, 3, 1, 1, 3, 1, 1, 1, 2, 3,

In [55]:
clf.score(X_train,y_train)#準確度分析


0.990625

In [56]:
clf.score(X_validation,y_validation)#準確度分析

0.9675

In [57]:
clf_matrics = metrics.confusion_matrix(y_validation,y_pre) #(真實值，預測值) 混淆矩陣
clf_matrics 

array([[ 88,   0,   0,   0],
       [  1,  95,   2,   0],
       [  0,   4, 105,   5],
       [  0,   0,   1,  99]], dtype=int64)

In [58]:
#Y X  0  1  2  3  Y預測答案 X真實答案 
#0   250 0  0  0
#1    0 234 0  0
#2    0  0 255 0
#3    0  0  0 261

In [59]:
from sklearn.metrics import precision_recall_fscore_support
print("Accuracy:",metrics.accuracy_score(y_validation, y_pre))#準確率
print("Precision:",metrics.precision_score(y_validation,y_pre,average=None))#精準度
print("Recall:",metrics.recall_score(y_validation,y_pre,average=None))#召回率
print("F1_score:",metrics.f1_score(y_validation,y_pre,average=None))#F1-score 


Accuracy: 0.9675
Precision: [0.98876404 0.95959596 0.97222222 0.95192308]
Recall: [1.         0.96938776 0.92105263 0.99      ]
F1_score: [0.99435028 0.96446701 0.94594595 0.97058824]


In [60]:
precision_recall_fscore_support(y_validation,y_pre,average=None) #support

(array([0.98876404, 0.95959596, 0.97222222, 0.95192308]),
 array([1.        , 0.96938776, 0.92105263, 0.99      ]),
 array([0.99435028, 0.96446701, 0.94594595, 0.97058824]),
 array([ 88,  98, 114, 100], dtype=int64))

In [61]:
X_test = test_data[['battery_power','blue','clock_speed','dual_sim','fc',
'four_g','int_memory','m_dep','mobile_wt','n_cores','pc','px_height',
'px_width','ram','sc_h','sc_w','talk_time','three_g','touch_screen','wifi']]

In [62]:
Y_test = clf.predict(X_test)#預測
Y_test

array([3, 3, 2, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 0, 2, 0, 2, 1, 3, 2, 1, 3,
       1, 1, 3, 0, 2, 0, 3, 0, 2, 0, 3, 0, 0, 1, 3, 1, 2, 1, 1, 2, 0, 0,
       0, 1, 0, 3, 1, 2, 1, 0, 3, 0, 3, 1, 3, 1, 1, 3, 3, 3, 0, 1, 1, 1,
       2, 3, 1, 2, 1, 2, 2, 3, 3, 0, 2, 0, 2, 3, 0, 3, 3, 0, 3, 0, 3, 1,
       3, 0, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 0, 0, 3, 0, 2, 0, 1, 2, 3,
       3, 3, 1, 3, 3, 3, 3, 2, 3, 0, 0, 3, 2, 1, 2, 0, 3, 2, 3, 2, 0, 2,
       1, 1, 3, 1, 1, 0, 3, 2, 1, 2, 1, 3, 2, 3, 3, 3, 2, 3, 2, 3, 1, 0,
       3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 1, 0, 3, 0, 0, 0, 2, 1, 0, 1,
       0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 0, 3, 1, 0, 2, 2,
       3, 3, 1, 1, 2, 2, 3, 2, 2, 1, 1, 0, 1, 2, 0, 2, 3, 3, 0, 2, 0, 3,
       2, 3, 3, 1, 0, 1, 0, 3, 0, 1, 0, 2, 2, 1, 3, 1, 3, 0, 3, 1, 2, 0,
       0, 2, 1, 3, 3, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 1, 1, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 1, 2, 3, 1, 1, 3, 2, 1, 3, 0, 1, 2, 1, 0, 3, 2, 3,
       3, 2, 1, 3, 3, 2, 3, 1, 2, 1, 2, 0, 2, 3, 1,